### ISSUE TITLE
Metrics Data Point not continuous showing on GCP Monitoring Dashboard

### ISSUE THREAD

**Issue by owensulei3841** [GoogleCloudPlatform/opentelemetry-operations-java#262]
Hi All,

Currently, I deployed my java application container, opentelemetry collector container into GKE. And in my collector, I send metrics to multiple vendors like: splunk, gcp, and so on. I see all metrics chart are showing the data continuously but only GCP Monitoring Dashboard showing Discrete data point.

This is my metrics chart:
![Screenshot 2023-09-18 at 10 28 33 PM](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/assets/33892816/c1b32f54-5f4b-4d94-8437-4731cc62a331)

This is the same metric on the gcp monitoring chart:
![Screenshot 2023-09-18 at 10 28 41 PM](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/assets/33892816/95f7777e-b7ac-4318-847c-729e0f19f9da)

I created a sh file in my application container to call my api 24/7. So I should get metrics data point all the time.
But I contact with gcp support, they said they only saw few data point I send, and I may not setup my collector correctly (Like how frequently sent data to gcp).

This is my opentelemetry collector runtime.yaml file, can I ask what I missing here? 
Should I configure how frequent send data to gcp in the googlecloud exporter section?
```yaml
 receivers:
    otlp:
      protocols:
        grpc:

  processors:
    memory_limiter:
      check_interval: 10s
      limit_percentage: 70
      spike_limit_percentage: 30

    batch:
      send_batch_max_size: 1024
      send_batch_size: 800
      timeout: 5s

  exporters:
    googlecloud:
      log:
        default_log_name: opentelemetry.io/collector-exported-log

  service:
    telemetry:
      logs:
        level: "debug"
        output_paths: [./telemetry.log]
    pipelines:
      metrics:
        receivers: [ otlp ]
        processors: [ memory_limiter, batch ]
        exporters: [ googlecloud]
```

Thank you
